---
title: "Session 4 Hausaufgabe, Alvin Aziz"
output: html_notebook
---

```{r}
library(tidyverse)
library(e1071)
library(caret)
library(pROC)
```

```{r}
titanic <- read_delim("titanic.csv", ";", 
    escape_double = FALSE, trim_ws = TRUE)
```
# Anzahl der Überlebenden und nicht Überlebten
```{r}
titanic %>%
  group_by(survived) %>%
  summarize(count = n())
```
# Anzahl der Überlebenden pro Geschlecht
```{r}
(titanicSurXGen <- titanic %>%
  select(survived,sex)) %>%
  filter(survived == 1) %>%
  group_by(sex) %>% 
  summarize(survivorGender = n())
```
# Anzahl der Überlebenden pro Klasse
```{r}
(titanicSurXClass <- titanic %>%
  select(survived,pclass)) %>%
  filter(survived == 1) %>%
  group_by(pclass) %>% 
  summarize(survivorClass = n())
```
# Anzahl der Reisenden, die als Einzelperson gereist sind vergleichen mit der Anzahl der Reisenden, die deren Familienmitglieder ebenfalls mitgereist sind.
```{r}
titanicCompare1 <- titanic %>% 
  select(survived, sibsp, parch)

(titanicSingle <- titanicCompare1 %>% 
  filter(sibsp == 0, parch == 0) %>% 
  group_by(survived) %>% 
  summarise(titanicSingle = n()))

(titanicFamilies <- titanicCompare1 %>% 
  filter(sibsp > 0, parch > 0) %>%   
  group_by(survived) %>% 
  summarise(titanicFamilies = n()))
```
