---
title: "Session 3 Hausaufgabe, Alvin Aziz"
output: html_notebook
---

```{r}
library(tidyverse)
library(arules)
library(arulesViz)
```

```{r}
all <- read_csv("all.csv")
```
```{r}
all$`Book-Author` <- sapply(all$`Book-Author`,function(row) iconv(row, "latin1", "ASCII", sub=""))
all %>% 
  mutate(`Book-Author` = tolower(`Book-Author`))
  write_csv(all, "all2.csv")
```

# Erstellen Sie eine Analyse, bei der nicht die Bücher, sondern die Autoren in den Transaktionen enthalten sind

```{r message=FALSE}
i <- split(all$`Book-Author`,all$`User-ID`)
txn <- as(i, "transactions")
basket_rules <- apriori(txn, parameter = list(sup = 0.0015, conf = 0.001, minlen=2, target="rules"))
```

```{r}
myRules_Direct <- as(basket_rules, "data.frame")
basket_rules_hi <- head(basket_rules, by ="lift",100)
head(myRules_Direct, 20)
```

```{r}
plot(basket_rules_hi, method="graph", main="Books", engine="interactive")
```

# Fällt Ihnen etwas in der Datenqualität auf?
# Beim Anzeigen der Ergebnisse, sieht man, dass es Clusters gibt, die die gleiche Autoren enthalten.

# Wie könnte man das mit regulären Ausdrücken beheben?
# ```{r}
# all$`Book-Author` <- sapply(all$`Book-Author`,function(row) iconv(row, "latin1", "ASCII", sub=""))

# all %>% 
#  mutate(`Book-Author` = tolower(`Book-Author`))
# ```


